/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.text.SimpleDateFormat;
import java.util.Date;
import static view.TelaRodadas.qtdRod;
import java.util.Random;
import static javax.print.attribute.Size2DSyntax.MM;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static view.TelaInformac.idade;
import static view.TelaInformac.nome;
import static view.TelaInformac.sexo;
import static view.TelaRandom.acerto;
import static view.TelaRandom.erro;
import static view.TelaRandom.min;
import static view.TelaRandom.nm;
import static view.TelaRandom.ns;
import static view.TelaRandom.seg;

/**
 *
 * @author Igor
 */
public class TelaRelatorio extends javax.swing.JFrame {

    private String acertos;

    /**
     * Creates new form TelaRelatorio
     */
    
/////////////////////

    public TelaRelatorio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btmInicio = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblNomePaciente = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        lblIdade = new javax.swing.JLabel();
        lblRodadas = new javax.swing.JLabel();
        lblAcertos = new javax.swing.JLabel();
        lblErros = new javax.swing.JLabel();
        lblPercAcerto = new javax.swing.JLabel();
        lblPercErros = new javax.swing.JLabel();
        lblTempoMinutos = new javax.swing.JLabel();
        lblTempoMedio = new javax.swing.JLabel();
        btmNovaSessao = new javax.swing.JToggleButton();
        btmNovoPaciente = new javax.swing.JToggleButton();
        btmGerar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        lblTempoSegundos = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblTentativas = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PRAEGRESSUS");

        btmInicio.setText("Inicio");
        btmInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmInicioActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome do paciente:");

        jLabel2.setText("Idade:");

        jLabel3.setText("Quantidade de Rodadas:");

        jLabel4.setText("Tempo Total:");

        jLabel5.setText("Tempo médio(s):");

        jLabel6.setText("Acertos:");

        jLabel7.setText("Erros:");

        jLabel8.setText("Data:");

        jLabel9.setText("Sexo:");

        jLabel10.setText("% Acerto:");

        jLabel11.setText("%  Erros:");

        lblData.setText(" ");

        lblSexo.setText("  ");

        lblIdade.setText("  ");

        lblRodadas.setText("  ");

        lblAcertos.setText("  ");

        lblErros.setText("  ");

        lblPercAcerto.setText("  ");

        lblPercErros.setText("  ");

        lblTempoMinutos.setText("00");
        lblTempoMinutos.setToolTipText("");

        lblTempoMedio.setText("  ");

        btmNovaSessao.setText("Nova Sessão");
        btmNovaSessao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmNovaSessaoActionPerformed(evt);
            }
        });

        btmNovoPaciente.setText("Novo Paciente");
        btmNovoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmNovoPacienteActionPerformed(evt);
            }
        });

        btmGerar.setText("Gerar");
        btmGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmGerarActionPerformed(evt);
            }
        });

        jLabel13.setText(":");

        lblTempoSegundos.setText("00");

        jLabel14.setText("Tentativas:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(btmGerar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                                .addComponent(btmNovoPaciente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btmNovaSessao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btmInicio))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(16, 16, 16)
                                        .addComponent(lblErros)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblPercErros))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(4, 4, 4)
                                        .addComponent(lblAcertos)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblPercAcerto)))
                                .addGap(64, 64, 64)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTempoMedio)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblTempoMinutos)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblTempoSegundos)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblData)
                        .addGap(64, 64, 64))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIdade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSexo)
                        .addGap(67, 67, 67))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(lblNomePaciente))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblRodadas))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTentativas)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblData))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblNomePaciente))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9)
                    .addComponent(lblSexo)
                    .addComponent(lblIdade))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblRodadas))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10)
                    .addComponent(jLabel4)
                    .addComponent(lblAcertos)
                    .addComponent(lblPercAcerto)
                    .addComponent(lblTempoMinutos)
                    .addComponent(jLabel13)
                    .addComponent(lblTempoSegundos))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11)
                    .addComponent(jLabel5)
                    .addComponent(lblErros)
                    .addComponent(lblPercErros)
                    .addComponent(lblTempoMedio))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(lblTentativas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btmInicio)
                    .addComponent(btmNovaSessao)
                    .addComponent(btmNovoPaciente)
                    .addComponent(btmGerar))
                .addContainerGap())
        );

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void btmInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmInicioActionPerformed
        // TODO add your handling code here:
        TelaInformac TelaInf = new TelaInformac();
        TelaInf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btmInicioActionPerformed

    private void btmNovaSessaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmNovaSessaoActionPerformed
        TelaRodadas TelaRod = new TelaRodadas();
        TelaRod.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btmNovaSessaoActionPerformed

    private void btmNovoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmNovoPacienteActionPerformed
        TelaInformac TelaInf = new TelaInformac();
        TelaInf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btmNovoPacienteActionPerformed
    static String idd;
    static String sx;
    static String qtd2;
    static String seg2;
    static Integer ns2;
    static Integer nm2;
    static Integer nts;
    
    private void btmGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmGerarActionPerformed
        // TODO add your handling code here:
        lblNomePaciente.setText(nome);
        idd = Integer.toString(idade);
        lblIdade.setText(idd);
      
        //sx = ;
        lblSexo.setText(sexo);
        lblData.setText(new SimpleDateFormat("dd/MM/yyyy").format(new Date()));
        qtd2 = Integer.toString(qtdRod);
        lblRodadas.setText(qtd2);
        
        //seg2 = Integer.toString(seg);
        lblTempoSegundos.setText(Integer.toString(ns));
        lblTempoMinutos.setText(Integer.toString(nm));
        //n1 segundos e n2 minutos
        ns2 = Integer.parseInt(lblTempoSegundos.getText());
        nm2 = Integer.parseInt(lblTempoMinutos.getText());
        
        nts = (nm2 * 60) + ns2 ;
        int q = Integer.parseInt(lblRodadas.getText());
        //JOptionPane.showMessageDialog(null, "noma em segundos"+nts);
        lblTempoMedio.setText((nts/q)+" segundos");
        
        lblAcertos.setText(""+acerto);
        
        lblErros.setText(""+erro);
        
        int s = erro+acerto;
        lblTentativas.setText(""+s);
        
        double pA;
        pA = (acerto*100)/s;
        lblPercAcerto.setText(pA+"%");
        double pE;
        pE = 100 - pA;
        lblPercErros.setText(pE+"%");
        
        
        //b1.setVisible(true);
    }//GEN-LAST:event_btmGerarActionPerformed


    /**
     * @param args the command line arguments
     */
    static String qt;    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmGerar;
    private javax.swing.JToggleButton btmInicio;
    private javax.swing.JToggleButton btmNovaSessao;
    private javax.swing.JToggleButton btmNovoPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAcertos;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblErros;
    private javax.swing.JLabel lblIdade;
    private javax.swing.JLabel lblNomePaciente;
    private javax.swing.JLabel lblPercAcerto;
    private javax.swing.JLabel lblPercErros;
    private javax.swing.JLabel lblRodadas;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTempoMedio;
    private javax.swing.JLabel lblTempoMinutos;
    private javax.swing.JLabel lblTempoSegundos;
    private javax.swing.JLabel lblTentativas;
    // End of variables declaration//GEN-END:variables


}
